### ISSUE TITLE
Braze SDK endpoints are incorrect 

### ISSUE THREAD

**Issue by trevinoa** [segment-integrations/analytics.js-integration-appboy#20]
Hey @Flaque - heads up, the SDK URLs are incorrect in this recent update. Correct format is:
`https://sdk.iad-01.braze.com` 01 through 03 for US
`https://sdk.fra-01.braze.eu` 01 only for EU

Reference doc:
https://www.braze.com/documentation/FAQs/#which-sdk-endpoint-do-i-use

cc @froodian

**Comment by Flaque** [comment]
Whoops! Thanks for letting us know! ❤️
